### ISSUE TITLE
Postgres credentials supplied by official Dokku Postgresql plugin don't work

### ISSUE THREAD

**Issue by etherealite** [claudyus/dokku-odoo#1]
The username supplied by the Postgresql service provided by the official Dokku plugin doesn't work with odoo's security check. The Dokku plugin supplies a username of __postgress__, which odoo refuses to use, as it thinks that the name is insecure.

How were you able to work around this issue?

**Comment by claudyus** [comment]
Hi @etherealite,

honestly I don't use the dokku postgresql plugin atm because last time I check the api cli command was really unstable. I manage the DBs in "legacy" mode and so the dokku-odoo instance is connected to DBs using network (VPC) when needed.

I checked the dokku-postgres plugin [1] and the odoo code [2] that forbid this use case and I believe that a lot of strategy could be follow to remove the problem:
A. propose, to the dokku guys, to add an option to modify the default username
B. patch the odoo code (simple removing the sys.exit line ) during dokku-odoo building
C. propose an option to odoo that disable those "security" check

I would be happy to merge a PR if you want to implement option B

BR

1. https://github.com/dokku/dokku-postgres
2. https://github.com/odoo/odoo/blob/fc2e80cb4bcc450762c7ac5cb82a3e2d88062b38/odoo/cli/server.py#L41

**Comment by etherealite** [comment]
Thanks @claudyus, I had the same idea as B. In the end, the simple solution was to get a docker shell in the postgresql container and manually create a new user. I only have one instance of Odoo so the lack of automation in this regard is tolerable.


I think your B solution is the only way to proceed to fix this image. Because the Odoo guys don't have the greatest reputation for responding to pull requests, I don't think they can be relied upon for a fix on this edge case.


When I gain some experience with the Odoo codebase I will revisit this issue. Thanks for your help, this image really smoothed things along for me.

**Comment by claudyus** [comment]
Hey @etherealite did you implement this? I would be happy to merge your fix

**Comment by etherealite** [comment]
I haven't had much time to ponder this. I do think that the best solution is somehow automatically apply patches to the parts of odoo that you specified in that disable the check.

> B. patch the odoo code (simple removing the sys.exit line ) during dokku-odoo building`
>1. https://github.com/dokku/dokku-postgres
>2. https://github.com/odoo/odoo/blob/fc2e80cb4bcc450762c7ac5cb82a3e2d88062b38/odoo/cli/server.py#L41

I'm also learning that the official Odoo image kind of sucks. It uses the Apt package install method, which forces you to break install an ancient version of Python PIP. This is then combined with the fact that Docker images are a second class citizen with Dokku, which is leading me to believe that custom buildpacks are a better  but more complex solution.

What do you think?

**Comment by bfontaine** [comment]
Why was this removed in a2afb73ea1401727809b2f0009dafc75d006a16e? The `patches` directory is still there, but the `Dockerfile` doesn’t apply the patches anymore. See also https://github.com/claudyus/dokku-odoo/issues/2#issuecomment-2417189831.
